# Generated by Django 4.2.7 on 2023-11-17 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=10, unique=True)),
                ('permissions', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Can Create'), (2, 'Can Read'), (3, 'Can Update'), (4, 'Can Delete')], max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Rollar',
                'verbose_name_plural': 'Rollar',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roles', models.ManyToManyField(blank=True, null=True, to='app.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ulanyjylar',
                'verbose_name_plural': 'Ulanyjylar',
            },
        ),
    ]
