# Generated by Django 4.2.7 on 2023-11-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(blank=True, to='app.roles'),
        ),
    ]
