# Generated by Django 4.2.7 on 2023-11-29 14:53

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_users_account_role_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='users',
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='permission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('create', 'CREATE'), ('red', 'RED'), ('update', 'UPDATE'), ('delete', 'DELETE')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='userpermission',
            name='permission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('create', 'CREATE'), ('red', 'RED'), ('update', 'UPDATE'), ('delete', 'DELETE')], max_length=10),
        ),
    ]
