# Generated by Django 4.2.7 on 2023-11-19 14:57

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='permission',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Create'), (2, 'Red'), (3, 'Update'), (4, 'Delete')], max_length=10),
        ),
        migrations.RemoveField(
            model_name='users',
            name='roles',
        ),
        migrations.AddField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(to='app.role'),
        ),
    ]
