# Generated by Django 4.2.7 on 2023-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_users_permission_remove_users_roles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='roles',
            field=models.ManyToManyField(blank=True, to='app.role'),
        ),
    ]
