# Generated by Django 4.2.7 on 2023-11-29 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_account_is_active_role_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='is_active',
        ),
    ]
